### ISSUE TITLE
parser is incorrect

### ISSUE THREAD

**Issue by Raynos** [bjouhier/i-json#9]
Tried parsing the following file with both c++ & javascript implementation

```json
[
  {
    "key": "datacenter",
    "city_id": 302,
    "value": "us-east1"
  },
  {
    "key": "datacenter.redirect",
    "city_id": 301,
    "value": false
  },
  {
    "key": "territory.enabled",
    "city_id": 300,
    "value": false
  },
  {
    "key": "webview.enabled",
    "city_id": null,
    "value": false
  },
  {
    "key": "express.version",
    "city_id": null,
    "value": 3
  }
]
```

The C++ parser reported the last value as `0` instead of `3`. The js parser threw an uncaught.

**Comment by bjouhier** [comment]
@Raynos Thanks for the repro. This module was an experiment and we haven't used it in production code yet. But maybe one day... 

I fixed the bug but I cannot guarantee that it does not have other holes like this one.
